### ISSUE TITLE
Tensorflow not downloading the NN

### ISSUE THREAD

**Issue by jesusdpa1** [hammerlab/cytokit#21]
Hi Eric, 

I am trying to run cytokit on a new pc and got the following error:

![image](https://user-images.githubusercontent.com/17010046/73108723-0ae2a780-3ecf-11ea-97a3-da8ff6bbf5de.png)

I have notice that the network is not being download when doing a clean start. I am not sure if that could be the problem.

The new PC has the following configuration:
Memory 128Gb
CPU: Intel Xeon W-2155
GPU: Quadro RTX 5000 12Gb

The image set that I am trying to analyze is 9x7 20 planes 9 cycles

I have try normal configuration and adjusted as suggested in the previous error report, with less number of planes and cycles but I still got the same error,

**Comment by eric-czech** [comment]
It happens when one of the files downloaded as a part of [this](https://github.com/hammerlab/cytokit/blob/master/python/pipeline/cytokit/data.py#L73) initialization end up being incomplete or empty.  You can delete them at ```/lab/data/.cytokit/cache/best_focus/model``` and run it again.  I don't know why the downloads sometimes fail, but that's the code that does it.

**Comment by jesusdpa1** [comment]
Thanks Eric, problem solve!

**Comment by eric-czech** [comment]
Awesome!  I'll close this out then.
