### ISSUE TITLE
Upgrading Python

### ISSUE THREAD

**Issue by mkeays** [hammerlab/cytokit#30]
Hi @eric-czech ,

We noticed that the Cytokit container has Python 3.5, and were wondering whether it's possible/how much work it would be to upgrade to a later version of Python (3.6. or higher)? Is there a specific reason for using 3.5?

Thanks!
Maria

**Comment by eric-czech** [comment]
It was pinned to 3.5.2 because that was the same version in use by the TF container being inherited from.  I imagine everything will be fine to upgrade as long as none of the pinned dependencies have a < 3.6 requirement, and it should simply fail to build if that's the case. 

Actually doing the upgrade hypothetically shouldn't involve much more than bumping the python version in the Dockerfile at the conda env creation step.  I wouldn't be surprised if an issue or two arises in the new build process but assuming you can clear them and get the tests to pass, you should be good to go.

**Comment by mkeays** [comment]
Thanks @eric-czech , we may try to do this and let you know how it goes :)
